/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ATCMainPanel.java
 *
 * Created on 02-Jul-2010, 19:36:55
 */

package Vidu.ATC.CommandCenter;

/**
 *
 * @author Viduruvan Suvinith Godawaththa <viduruvans at gmail.com> @ viduruvan.net
 */
public class ATCMainPanel extends javax.swing.JFrame {

    /** Creates new form ATCMainPanel */
    public ATCMainPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lpnldepHead = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lpnlDepPlane1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lpnlDepPlane2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lpnldepHead.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout lpnldepHeadLayout = new javax.swing.GroupLayout(lpnldepHead);
        lpnldepHead.setLayout(lpnldepHeadLayout);
        lpnldepHeadLayout.setHorizontalGroup(
            lpnldepHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        lpnldepHeadLayout.setVerticalGroup(
            lpnldepHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lpnldepHead.setBounds(710, 0, 180, 100);
        jLayeredPane1.add(lpnldepHead, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        lpnlDepPlane1.setLayout(null);
        jPanel1.add(lpnlDepPlane1);
        lpnlDepPlane1.setBounds(10, 10, 160, 70);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 160, 70);

        jPanel4.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel4.setLayout(null);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 170, 160, 80);

        jPanel5.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel5.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel5.setLayout(null);
        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 260, 160, 80);

        jPanel6.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel6.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel6.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel6.setLayout(null);
        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 350, 160, 80);

        jPanel7.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel7.setLayout(null);
        jPanel1.add(jPanel7);
        jPanel7.setBounds(10, 440, 160, 80);

        jPanel8.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel8.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel8.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel8.setLayout(null);
        jPanel1.add(jPanel8);
        jPanel8.setBounds(10, 530, 160, 80);

        jPanel9.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel9.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel9.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel9.setLayout(null);
        jPanel1.add(jPanel9);
        jPanel9.setBounds(10, 620, 160, 90);

        jPanel10.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel10.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel10.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel10.setLayout(null);
        jPanel1.add(jPanel10);
        jPanel10.setBounds(10, 720, 160, 80);

        jPanel11.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel11.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel11.setPreferredSize(new java.awt.Dimension(160, 70));
        jPanel11.setLayout(null);
        jPanel1.add(jPanel11);
        jPanel11.setBounds(10, 810, 160, 80);

        jPanel1.setBounds(710, 110, 180, 930);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lpnlDepPlane2.setLayout(null);
        lpnlDepPlane2.setBounds(0, 0, 0, 0);
        jLayeredPane1.add(lpnlDepPlane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setMaximumSize(new java.awt.Dimension(160, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(160, 70));
        jPanel3.setLayout(null);
        jPanel3.setBounds(0, 0, 160, 70);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATCMainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel lpnlDepPlane1;
    private javax.swing.JPanel lpnlDepPlane2;
    private javax.swing.JPanel lpnldepHead;
    // End of variables declaration//GEN-END:variables




   
}
