/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlaneSetter.java
 *
 * Created on 03-Jun-2010, 19:08:14
 */

package Vidu.ATC.CommandCenter;

import Vidu.ATC.Flights.DriveController;
import Vidu.ATC.Flights.LandingController;
import Vidu.ATC.Flights.Mode;
import Vidu.ATC.Flights.Plane;
import Vidu.ATC.Flights.PlaneController;
import Vidu.ATC.Flights.PlanePiority;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Viduruvan Suvinith Godawaththa <viduruvans at gmail.com> @ viduruvan.net
 */
public class PlaneSetter extends javax.swing.JFrame {

    /** Creates new form PlaneSetter */
    public PlaneSetter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTopicAirPlaneSetup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbMode = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cmbPiority = new javax.swing.JComboBox();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame Setter");
        setResizable(false);

        lblTopicAirPlaneSetup.setFont(new java.awt.Font("Arial Black", 1, 18));
        lblTopicAirPlaneSetup.setText("Setup Air Plane");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Mode");

        txtName.setText("Enter Plane Name");

        cmbMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Plane Mode", "LANDING", "NEUTRAL", "TAKEOFF" }));
        cmbMode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemChanged(evt);
            }
        });
        cmbMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setText("Piority");

        cmbPiority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Piority Type", "Normal", "Medical", "Fuelshortage", "Micanical", "Other" }));
        cmbPiority.setEnabled(false);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(128, 128, 128)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addComponent(lblTopicAirPlaneSetup, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(94, 94, 94)
                        .addComponent(cmbMode, 0, 209, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cmbPiority, 0, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopicAirPlaneSetup)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbPiority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancel))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        // to close the system
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Plane plane = null;
        PlaneController controller =null;
        Mode mode = null;
        PlanePiority planePiority = null;
        // Varible for plane creating

        String name = this.txtName.getText();
       // float speed = Float.parseFloat(this.txtSpeed.getText());
       // double fuel = Double.parseDouble(this.txtFuel.getText());
        Mode planeMode = mode;
        PlanePiority Piorty = planePiority;
         PlaneController planeController = null;


        // to check weather user selected Mode of the plane
        // if user not selected it provide an error message
        if(this.cmbMode.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,"<html>Sorry Invalid Selection in Mode Combo box.<Br>Please select a mode and try again.<Br>Thank you !</html> ");
        }
        // if user selected any option it assign relavent value to mode
        else{
            boolean con1 = this.cmbMode.getSelectedIndex() == 1;
            boolean con2 = this.cmbMode.getSelectedIndex() == 2;
            boolean con3 = this.cmbMode.getSelectedIndex() == 3;
            // if user selected Landing mode
            if(con1){
                       mode= Mode.LANDING;
                        plane = new Plane();
                        System.out.println("Plane Setter Mode Landing : Plane Created");
                        DriveController flightController = new  LandingController(plane);
                         System.out.println("Plane Setter Mode Landing : LandingController Created");
                         planeController = new PlaneController(flightController );
                        System.out.println("Plane Setter Mode Landing : planeController Created");

            }
            // if user selected flying mode
            else if (con2){
                mode=Mode.NUTRAL;

                // to check what is the piority
                // this will only acceble if user selected flying mode
                if(this.cmbPiority.getSelectedIndex()!=0){
                    boolean con4 = cmbPiority.getSelectedIndex()==4 ;
                    boolean con5 = cmbPiority.getSelectedIndex()==5 ;
                    con1 = cmbPiority.getSelectedIndex()==1 ;
                    con2 = cmbPiority.getSelectedIndex()==2 ;
                    con3 = cmbPiority.getSelectedIndex()==3 ;

                    // if user selected Normal mode
                    if(con1){
                        planePiority = PlanePiority.NORMAL;
                    }
                    // if user selected Medical
                    else if(con2){
                        planePiority = PlanePiority.MEDICAL;
                    }
                    //if user selcted fuel
                    else if(con3){
                        planePiority = PlanePiority.FUELSHORTAGE;
                    }
                    // if user selected micanical
                    else if(con4){
                        planePiority = PlanePiority.MICANICAL;
                    }
                    // if user selected Other
                    else if(con5){
                        planePiority = PlanePiority.OTHER;
                    }

                    // to asingn values to the variables

                    name = this.txtName.getText();
                   // speed = Float.parseFloat(this.txtSpeed.getText());
                  //  fuel = Double.parseDouble(this.txtFuel.getText());
                    planeMode = mode;
                    Piorty = planePiority;
                 

                    plane = new Plane();
                   // plane = new Plane(name,speed,fuel,Piorty,locationX,locationY,locationH,destinationX,destinationY);


                    // else user selected nothing

                    
                } else{
                    JOptionPane.showMessageDialog(this,"<html>Sorry Invalid Selection in Piority Combo box.<Br>Please select a mode and try again.<Br>Thank you !</html> ");

                }


            }

            // else user selected take off mode
            else {
                mode= Mode.TAKEOFF;
                this.cmbPiority.setEnabled(false);
                }
            //JOptionPane.showMessageDialog(this,mode.name().toString());
            // JOptionPane.showMessageDialog(this,planePiority.name().toString());
        }
        try {
            // to pass to plane contr
            /* We have to connect to the ATC*/
            planeController.connectToAtc();
            //  controller = new PlaneController(plane);
        } catch (Exception ex) {
            Logger.getLogger(PlaneSetter.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbModeActionPerformed

    private void ItemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ItemChanged
        if(this.cmbMode.getSelectedIndex() != 2) {
            this.cmbPiority.setEnabled(false);

        } else if(this.cmbMode.getSelectedIndex() == 2) {
            this.cmbPiority.setEnabled(true);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_ItemChanged

    // if cmbmode item changed it will check what is the selected item and determine weather it should enable Piority mode or not
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaneSetter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cmbMode;
    private javax.swing.JComboBox cmbPiority;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTopicAirPlaneSetup;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
